name: context_workflow
on: workflow_dispatch
jobs:
  build:
    name: "context_display"
    runs-on: ubuntu-latest
    steps:
    - name: showing github_context
      run: echo $GITHUB_CONTEXT
    - name: showing sectet context
      run: echo ${{secrets}}