name: context_workflow
on: workflow_dispatch
jobs:
  build:
    name: build job
    runs-on: ubuntu-latest
    steps:
      - name: check main 
        run: echo "hello from dhruv"
        if:  ${{ github.ref == 'refs/heads/main' }}