name: my_workflow
on:
  - push
jobs:
  build:
    name: build job
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout action
        uses: actions/checkout@v7

      - name: Installig cowsay
        run: sudo apt-get install cowsay -y
        
      - name: working with cowsay 
        run: |
          cowsay -f dragon "Run for the cover, save me dhruv" > dragon.txt
          cat dragon.txt
          
      - name: uploading artifact
        uses: actions/upload-artifact@v7
        with:
          name: dhruv.txt
          path: ./dragon.txt
          archive: true

  test:
    name: build_job
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    
      - name: Hello from test
        run: echo "Hello from test job "
        
      - name: downloading artifact
        uses: actions/download-artifact@v8
        with:
          name: dhruv.txt
          
      - name: Echoing the artifact
        run: |
          cat dhruv.txt
          
