name: my_workflow
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout action
        uses: actions/checkout@v7

      - name: cating 
        run: |
          ls
          echo "Reading README.md"
          cat README.md
